#
# Copyright (C) 2024 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

name: "table-caption-generate-V1_A"
model_id: "anthropic.claude-3-haiku-20240307-v1:0"
rate_limit:
  limit: 300
  period: day
template: |
  Generate a caption for the following HTML table from its preview.

  The caption should summarize the content of the table in a concise and 
  informative manner.

  The preview of table in HTML format is provided below:
  ```
  <HTML_TABLE_PLACEHOLDER>
  ```

  You can expect that the table will contain data similar to its preview.

  Limit the caption to 120 characters or less.

  Skip the preamble and return just the plain caption, without any quoting
  for the table.
options:
  max_tokens: 2000
